name: interact with Github API
on: 
  pull_request:

secrets:
  GITHUB_TOKEN: 
    ${{ secrets.GITHUB_TOKEN }}
    description: 'Token to interact with Github API'
    required: true

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: create issue
        shell: bash
        run: curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/PeterAlfonsLoch/my-react-app/issues \
          -d '{"title":"Found a bug","body":"I'\''m having a problem with this.","assignees":["octocat"],"milestone":1,"labels":["bug"]}'